### ISSUE TITLE
Question about using Miqro in phaser board

### ISSUE THREAD

**Issue by Yueh-H** [quartiq/miqro-sim#1]
I'm using the example you provided below. 
```

import logging
import numpy as np
from artiq.experiment import *
from artiq import *
   
logger = logging.getLogger(__name__)
   
class Miqro_v1(EnvExperiment):
def build(self):
        self.setattr_device("core")
        self.setattr_device("Miqro0")
        self.miqro0 = self.Miqro0

@kernel
def setup(self):
# Configure example data for some profiles on some oscillators
# e.g.: profile 3 on oscillator 11 will be 3 MHz, 0.3 amplitude full scale,
# -0.3 turn (coherent) phase
        for osc in [0, 4, 11]:
                for profile in [1, 2, 3]:
                delay(10*us)
                self.miqro0.set_profile(
                osc,
                profile,
                frequency=1 * MHz * (osc - 8),
                amplitude=0.1 * profile,
                phase=-0.1 * profile,
                )
        # Configure some window data and interpolation parameters
        iq = [(1, 0), (1, 0), (0, 1), (0, 1)]
        
        self.miqro0.set_window(start=0, iq=iq, period=128 * 4 * ns, order=3)

@kernel
def pulse(self):
        # Choose example profiles and phase offsets
        # profiles[oscillator index] = profile index
        profiles = [0] * 16
        profiles[0] = 1
        profiles[4] = 2
        profiles[11] = 3
        # Choose window start address
        window = 0x000
        higher rates.
        self.miqro0.pulse(window, profiles)
  
@kernel
        def run(self):
        self.core.reset()
        self.phaser.init()
        self.miqro0.reset()
        self.setup()
        self.pulse()
```

I'm getting the following error when connecting to a real Phaser board. Do you know what might be causing it?

ERROR:worker(3177,20230915_AWG_MIQROv1.py):root:Terminating with exception (DeviceError: Failed to create device 'Miqro0')
Traceback (most recent call last):
  File "/nix/store/qcx1lg4wdd5xj94jzpw8r8n9d5k0ckgb-python3-3.10.12-env/lib/python3.10/site-packages/artiq/master/worker_db.py", line 88, in get
    dev = _create_device(desc, self)
  File "/nix/store/qcx1lg4wdd5xj94jzpw8r8n9d5k0ckgb-python3-3.10.12-env/lib/python3.10/site-packages/artiq/master/worker_db.py", line 27, in _create_device
    return device_class(device_mgr, **desc.get("arguments", {}))
TypeError: Miqro.__init__() got multiple values for argument 'channel'
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/nix/store/qcx1lg4wdd5xj94jzpw8r8n9d5k0ckgb-python3-3.10.12-env/lib/python3.10/site-packages/artiq/master/worker_impl.py", line 331, in main
    exp_inst = exp((device_mgr, dataset_mgr, argument_mgr, {}))
  File "/nix/store/qcx1lg4wdd5xj94jzpw8r8n9d5k0ckgb-python3-3.10.12-env/lib/python3.10/site-packages/artiq/language/environment.py", line 254, in __init__
    self.build(*args, **kwargs)
  File "/home/rabi/artiq/repository/Miqro/20230915_AWG_MIQROv1.py", line 16, in build
    self.setattr_device("Miqro0")
  File "/nix/store/qcx1lg4wdd5xj94jzpw8r8n9d5k0ckgb-python3-3.10.12-env/lib/python3.10/site-packages/artiq/language/environment.py", line 338, in setattr_device
    setattr(self, key, self.get_device(key))
  File "/nix/store/qcx1lg4wdd5xj94jzpw8r8n9d5k0ckgb-python3-3.10.12-env/lib/python3.10/site-packages/artiq/language/environment.py", line 331, in get_device
    return self.__device_mgr.get(key)
  File "/nix/store/qcx1lg4wdd5xj94jzpw8r8n9d5k0ckgb-python3-3.10.12-env/lib/python3.10/site-packages/artiq/master/worker_db.py", line 90, in get
    raise DeviceError("Failed to create device '{}'"
artiq.master.worker_db.DeviceError: Failed to create device 'Miqro0'
ERROR:master:artiq.master.scheduler:got worker exception in prepare stage, deleting RID 3177

My device_db.py file looks like this. Have I missed something?

```
device_db["Miqro0"] = {
"type": "local",
"module": "artiq.coredevice.phaser",
"class": "Miqro",
"arguments": {"channel": 0x010000 }
}
```

Or, do you have any actual examples of running mqiro on Phaser? Thank you

**Comment by jordens** [comment]
Your device db is invalid but that's not going to be the crucial issue. As explained in the artiq documentation for phaser the gateware on phaser, the gateware on kasli and the core device driver need to match. The miqro phaser gateware is not public. If your use case has distinct specifications that meet the features of MIQRO, feel free to contact me to discuss options.
